# version: '3.9'
services:
  db:
    image: mysql:8
    container_name: notes_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_password
      MYSQL_DATABASE: notes_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: notes_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: notes_frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

volumes:
  db_data:
